apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clientservice-hpa
  namespace: gestor-tareas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clientservice-deployment
  minReplicas: 1
  maxReplicas: 5 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50